pluginManagement {
    repositories {
        gradlePluginPortal()
        mavenCentral()
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.PREFER_SETTINGS)
    repositories {
        mavenCentral()
    }
}

rootProject.name = 'backend'
include 'core-domain', 'core-application', 'app-api',
        'support-cache-redis', 'support-persistence', 'support-notification-mail', 'support-storage'
        'boot'

include 'support-storage'